services:

    # First service = Reddit Collector
    reddit_collector:
        build: reddit_collector/
        volumes:
            - ./reddit_collector/:/app
        depends_on:
            - mongodb

    # Second service = Mongo
    mongodb:
        image: mongo
        ports:
            - 27017:27017

    # Third service = ETL
    etl:
        build: etl_job/
        volumes:
            - ./etl_job/:/app
        depends_on:
            - mongodb
            - my_postgres

    # Fourth service = Postgres
    my_postgres:
        image: postgres
        ports:
            - 5555:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=reddits_pgdb
    
    # Fith service = slack_bot
    slack_bot:
        build: slackbot/
        volumes:
            - ./slackbot/:/app
        depends_on:
            - etl

    # In this case, 'postgres' is being used as the default username and password 
    # for the PostgreSQL database.